version: '3.8'

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - WEBHOOK_URL=http://localhost:5678
      - N8N_DEFAULT_BINARY_DATA_MODE=filesystem
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
    volumes:
      - ./n8n-data:/home/node/.n8n
    depends_on:
      - baserow
      - minio
      - kokoro-tts
      - nca-toolkit
    restart: unless-stopped
    networks:
      - app-network

  minio:
    image: quay.io/minio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --address ":9000" --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password123
    volumes:
      - ./minio-data:/data
    restart: unless-stopped
    networks:
      - app-network

  kokoro-tts:
    image: ghcr.io/remsky/kokoro-fastapi-cpu:v0.2.2
    container_name: kokoro-tts
    ports:
      - "8880:8880"
    environment:
      - PORT=8880
    restart: unless-stopped
    networks:
      - app-network

  baserow:
    image: baserow/baserow:1.32.5
    container_name: baserow-app
    ports:
      - "85:80"
      - "443:443"
      - "3000:3000"
    environment:
      - BASEROW_PUBLIC_URL=http://baserow:80
      - BASEROW_CADDY_ADDRESSES=:80
    volumes:
      - ./baserow-data:/baserow/data
    restart: unless-stopped
    shm_size: "256mb"
    networks:
      - app-network

  nca-toolkit:
    image: stephengpope/no-code-architects-toolkit:latest
    container_name: nca-toolkit
    ports:
      - "8080:8080"
    environment:
      - API_KEY=thekey
      - S3_ENDPOINT_URL=http://minio:9000
      - S3_ACCESS_KEY=admin
      - S3_SECRET_KEY=password123
      - S3_BUCKET_NAME=nca-toolkit
      - S3_REGION=None
      - PORT=8080
    depends_on:
      - minio
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge