version: '3.8'

services:

  kokoro-tts:
    image: ghcr.io/remsky/kokoro-fastapi-gpu:v0.2.2
    container_name: kokoro-tts
    ports:
      - "8880:8880"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - PORT=8880
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped

  nca-toolkit:
    image: stephengpope/no-code-architects-toolkit:latest
    container_name: nca-toolkit
    ports:
      - "8080:8080"
    environment:
      - API_KEY=thekey
      - S3_ENDPOINT_URL=http://raspberryvibe:9000
      - S3_ACCESS_KEY=admin
      - S3_SECRET_KEY=password123
      - S3_BUCKET_NAME=nca-toolkit
      - S3_REGION=None
      - S3_PORT=8080
    extra_hosts:
      - "raspberryvibe:192.168.1.223"
    restart: unless-stopped

volumes:
  ollama_data:
